kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
name: multi-env-cluster
nodes:
- role: control-plane
  extraPortMappings:
  - containerPort: 30080
    hostPort: 30080
    protocol: TCP
  - containerPort: 30081
    hostPort: 30081
    protocol: TCP
  - containerPort: 30082
    hostPort: 30082
    protocol: TCP

#kind create cluster --config kind-config.yaml
